new KB - Eliminate the Last Item's stretching in DataLayout
telerik/winforms-docs pull request #401
Opened 2023-06-27 14:18 UTC by dessyordanova

2023-06-27 14:46 UTC, TodorVyagov requested changes
There are two controls added by default in RadLayoutControl - the horizontal and vertical scrollbars, so to have precise calculations, we need to subtract them.
In addition, the default size for editors in the Fluent theme is 24 pixels, so this increases the height per layout control item.
int height = (this.radDataLayout1.LayoutControl.Controls.Count - 2 ) * 24;

2023-06-27 14:46 UTC, TodorVyagov commented on knowledge-base/stretched-last-item-in-datalayout.md
> +            int height = this.radDataLayout1.LayoutControl.Controls.Count * 20;
There are two controls added by default in RadLayoutControl - the horizontal and vertical scrollbars, so to have precise calculations, we need to subtract them.
In addition, the default size for editors in the Fluent theme is 24 pixels, so this increases the height per layout control item.
int height = (this.radDataLayout1.LayoutControl.Controls.Count - 2 ) * 24;

2023-06-27 15:02 UTC, TodorVyagov commented on knowledge-base/stretched-last-item-in-datalayout.md
> +|2023.2.606|RadDataLayout for WinForms|[Dinko Krastev](https://www.telerik.com/blogs/author/desislava-yordanova)|
[Dinko Krastev]

2023-06-28 05:52 UTC, dessyordanova commented
Addressed the feedback.

2023-06-28 06:59 UTC, TodorVyagov approved these changes

2023-06-28 06:59 UTC, merged