RichTextEditor: Document the API that allows you to change the mouse …
telerik/winforms-docs pull request #665
Opened 2024-12-27 09:23 UTC by nade7o

…selection handler

2025-01-09 08:50 UTC, icom85 requested changes

2025-01-09 08:50 UTC, icom85 commented on telerik-presentation-framework/dpi-support.md
In the first section we better change to ... **starting with .NET Framework 4.6.2** ...  which is our lowest supported target framework.

2025-01-09 08:50 UTC, icom85 commented on telerik-presentation-framework/dpi-support.md
Maybe we will also need to update the two comparison images. In the later versions the images inside the RTE ribbon are SVG and they will appaer also crisp on HDPI.

2025-01-09 08:50 UTC, icom85 commented on telerik-presentation-framework/dpi-support.md
Not sure if it's a good idea to also add the [WinForms Scaling at Large DPI Settings–Is It Even Possible?](http://www.telerik.com/blogs/winforms-scaling-at-large-dpi-settings-is-it-even-possible-) also blog inside the DPI Awareness section as it provides some general and very useful information.

2025-01-09 08:50 UTC, icom85 commented on telerik-presentation-framework/dpi-support.md
We better change .NET 9 with .NET in this section:
 ## High DPI support in an Application targeting .NET 9

2025-01-09 14:01 UTC, nade7o commented on telerik-presentation-framework/dpi-support.md
Done.

2025-02-11 10:56 UTC, DinkoK approved these changes

2025-02-11 10:57 UTC, icom85 approved these changes

2025-02-11 10:57 UTC, merged

2025-02-11 10:57 UTC, DinkoK approved these changes